"""Provider boundary for the single-machine workflow.

The deterministic provider is for tests and local engineering demonstrations.
It never produces a diagnosis and makes no network calls.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Protocol

from medidiag.workflow.provider_runtime import ProviderResponse

# ProviderCallRunner.call accepts either shape from every stage: a bare payload,
# or a ProviderResponse carrying the request ID and provider counters needed for
# audit. DeepSeekWorkflowProvider.generate already returns the latter, so the
# Protocol has to admit both or it contradicts its only live implementation.
StageResult = dict | ProviderResponse


class WorkflowProvider(Protocol):
    version: str

    def normalize(self, question: str) -> StageResult: ...

    def retrieve(self, normalized_query: str) -> StageResult: ...

    def plan(self, normalized_query: str, retrieval: dict) -> StageResult: ...

    def generate(self, question: str, retrieval: dict, plan: dict) -> StageResult: ...

    def arbitrate(self, generation: dict, retrieval: dict) -> StageResult: ...

    def review(self, generation: dict, arbitration: dict) -> StageResult: ...

    def report(self, case_id: str, generation: dict, review: dict) -> StageResult: ...


@dataclass
class DeterministicWorkflowProvider:
    """Network-free provider with cautious, non-diagnostic fixture output."""

    review_verdict: str = "APPROVED"
    version: str = "deterministic-provider-v1"

    def normalize(self, question: str) -> dict:
        return {
            "normalized_query": " ".join(question.strip().lower().split()),
            "normalizer_version": self.version,
        }

    def retrieve(self, normalized_query: str) -> dict:
        chunk_id = "fixture_" + hashlib.sha256(
            normalized_query.encode("utf-8")
        ).hexdigest()[:12]
        return {
            "query": normalized_query,
            "top_k": 1,
            "config_hash": "deterministic-fixture",
            "chunks": [
                {
                    "chunk_id": chunk_id,
                    "source": "deterministic_test_fixture",
                    "source_id": "local-fixture-v1",
                    "evidence_level": "level_5_other",
                    "score": 1.0,
                    "text": (
                        "Available fixture evidence is insufficient for a definitive "
                        "diagnosis and requires qualified clinical review."
                    ),
                }
            ],
        }

    def plan(self, normalized_query: str, retrieval: dict) -> dict:
        return {
            "objective": "review supplied evidence without issuing a diagnosis",
            "evidence_ids": [item["chunk_id"] for item in retrieval["chunks"]],
            "requires_uncertainty": True,
        }

    def generate(self, question: str, retrieval: dict, plan: dict) -> dict:
        chunk_id = retrieval["chunks"][0]["chunk_id"]
        claim = {
            "claim_id": "claim_0001",
            "text": "Available evidence is insufficient for a definitive diagnosis.",
            "citation_chunk_ids": [chunk_id],
            "confidence": 1.0,
        }
        return {
            "agents": [
                {
                    "agent_name": "general_internal",
                    "status": "SUCCEEDED",
                    "claims": [claim],
                },
                {
                    "agent_name": "evidence_skeptic",
                    "status": "SUCCEEDED",
                    "claims": [claim],
                },
            ],
            "claims": [claim],
            "risk_flags": ["qualified_clinician_review_required"],
            "uncertainty": "No definitive diagnosis is generated by this fixture.",
        }

    def arbitrate(self, generation: dict, retrieval: dict) -> dict:
        return {
            "verdict": "CONSENSUS_WITH_LIMITATION",
            "selected_claim_ids": [item["claim_id"] for item in generation["claims"]],
            "conflicts": [],
            "limitation": "Deterministic engineering fixture; no clinical conclusion.",
        }

    def review(self, generation: dict, arbitration: dict) -> dict:
        verdict = self.review_verdict.upper()
        if verdict not in {"APPROVED", "REVISION_REQUIRED", "ESCALATED"}:
            raise ValueError(f"unsupported deterministic review verdict: {verdict}")
        return {
            "verdict": verdict,
            "issues": [] if verdict == "APPROVED" else ["human review required"],
            "citation_verdicts": [
                {
                    "claim_id": claim["claim_id"],
                    "chunk_id": claim["citation_chunk_ids"][0],
                    "verdict": "SUPPORTED",
                    "confidence": 1.0,
                    "method": "deterministic_fixture",
                }
                for claim in generation["claims"]
            ],
            "compliance_status": "PASSED_NON_DIAGNOSTIC_FIXTURE",
        }

    def report(self, case_id: str, generation: dict, review: dict) -> dict:
        return {
            "case_id": case_id,
            "title": "Evidence Review Draft",
            "summary": "No definitive diagnosis was generated.",
            "claims": generation["claims"],
            "limitations": [
                "Deterministic local fixture; not clinical evidence synthesis.",
                "Requires review by a qualified clinician.",
            ],
            "disclaimer": "仅供学习和工程演示，不构成医疗建议。",
        }
