"""单机工作流的 Provider 边界。

确定性 Provider 用于测试和本地工程演示；它从不生成诊断，也不会发起网络请求。
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Protocol

from medidiag.compliance.status import ComplianceStatus
from medidiag.workflow.provider_runtime import ProviderResponse

# ProviderCallRunner.call 接受每个阶段的两种返回形态：裸载荷，
# 或带有请求 ID 和 Provider 计数器的 ProviderResponse，后者用于
# 审计。DeepSeekWorkflowProvider.generate 已经返回后一种形态，因此
# Protocol 必须同时允许两者，否则会与唯一的在线实现矛盾。
StageResult = dict[str, Any] | ProviderResponse


class WorkflowProvider(Protocol):
    version: str

    def normalize(self, question: str) -> StageResult: ...

    def retrieve(self, normalized_query: str) -> StageResult: ...

    def plan(self, normalized_query: str, retrieval: dict[str, Any]) -> StageResult: ...

    def generate(self, question: str, retrieval: dict[str, Any], plan: dict[str, Any]) -> StageResult: ...

    def arbitrate(self, generation: dict[str, Any], retrieval: dict[str, Any]) -> StageResult: ...

    def review(
        self,
        generation: dict[str, Any],
        arbitration: dict[str, Any],
        retrieval: dict[str, Any],
    ) -> StageResult: ...

    def report(self, case_id: str, generation: dict[str, Any], review: dict[str, Any]) -> StageResult: ...


@dataclass
class DeterministicWorkflowProvider:
    """无网络、谨慎且不作诊断的 fixture Provider。"""

    review_verdict: str = "APPROVED"
    version: str = "deterministic-provider-v1"

    def normalize(self, question: str) -> dict[str, Any]:
        return {
            "normalized_query": " ".join(question.strip().lower().split()),
            "normalizer_version": self.version,
        }

    def retrieve(self, normalized_query: str) -> dict[str, Any]:
        chunk_id = "fixture_" + hashlib.sha256(
            normalized_query.encode("utf-8")
        ).hexdigest()[:12]
        return {
            "query": normalized_query,
            "top_k": 1,
            "config_hash": "deterministic-fixture",
            "chunks": [
                {
                    "chunk_id": chunk_id,
                    "source": "deterministic_test_fixture",
                    "source_id": "local-fixture-v1",
                    "evidence_level": "level_5_other",
                    "score": 1.0,
                    "text": (
                        "Available fixture evidence is insufficient for a definitive "
                        "diagnosis and requires qualified clinical review."
                    ),
                }
            ],
        }

    def plan(self, normalized_query: str, retrieval: dict[str, Any]) -> dict[str, Any]:
        return {
            "objective": "review supplied evidence without issuing a diagnosis",
            "evidence_ids": [item["chunk_id"] for item in retrieval["chunks"]],
            "requires_uncertainty": True,
        }

    def generate(self, question: str, retrieval: dict[str, Any], plan: dict[str, Any]) -> dict[str, Any]:
        chunk_id = retrieval["chunks"][0]["chunk_id"]
        claim = {
            "claim_id": "claim_0001",
            "text": "Available evidence is insufficient for a definitive diagnosis.",
            "citation_chunk_ids": [chunk_id],
            "confidence": 1.0,
        }
        return {
            "agents": [
                {
                    "agent_name": "general_internal",
                    "status": "SUCCEEDED",
                    "claims": [claim],
                },
                {
                    "agent_name": "evidence_skeptic",
                    "status": "SUCCEEDED",
                    "claims": [claim],
                },
            ],
            "claims": [claim],
            "risk_flags": ["qualified_clinician_review_required"],
            "uncertainty": "No definitive diagnosis is generated by this fixture.",
        }

    def arbitrate(self, generation: dict[str, Any], retrieval: dict[str, Any]) -> dict[str, Any]:
        return {
            "verdict": "CONSENSUS_WITH_LIMITATION",
            "selected_claim_ids": [item["claim_id"] for item in generation["claims"]],
            "conflicts": [],
            "limitation": "Deterministic engineering fixture; no clinical conclusion.",
        }

    def review(
        self,
        generation: dict[str, Any],
        arbitration: dict[str, Any],
        retrieval: dict[str, Any],
    ) -> dict[str, Any]:
        del arbitration, retrieval
        verdict = self.review_verdict.upper()
        if verdict not in {"APPROVED", "REVISION_REQUIRED", "ESCALATED"}:
            raise ValueError(f"unsupported deterministic review verdict: {verdict}")
        return {
            "verdict": verdict,
            "issues": [] if verdict == "APPROVED" else ["human review required"],
            "citation_verdicts": [
                {
                    "claim_id": claim["claim_id"],
                    "chunk_id": claim["citation_chunk_ids"][0],
                    "verdict": "SUPPORTED",
                    "confidence": 1.0,
                    "method": "deterministic_fixture",
                }
                for claim in generation["claims"]
            ],
            "compliance_status": ComplianceStatus.PASSED_NON_DIAGNOSTIC_FIXTURE.value,
        }

    def report(self, case_id: str, generation: dict[str, Any], review: dict[str, Any]) -> dict[str, Any]:
        return {
            "schema_version": "assistant-report-v1",
            "case_id": case_id,
            "title": "确定性证据审阅报告（测试 fixture）",
            "summary": "确定性 fixture 未生成明确诊断，仅用于工作流测试。",
            "claims": generation["claims"],
            "filtered_claim_count": 0,
            "risk_warnings": ["该结果不能用于真实医疗决策。"],
            "limitations": [
                "Deterministic local fixture; not clinical evidence synthesis.",
                "Requires review by a qualified clinician.",
            ],
            "next_steps": ["如有真实健康问题，请咨询具备资质的医疗专业人员。"],
            "disclaimer": "仅供学习和工程演示，不构成医疗建议。",
            "provenance": {"fixture": True},
        }
